/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import entities.*;
import entities.Tracker;
import entities.Vehicule;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.TrackerService;
import service.VehiculeGPSTrakerService;
import service.VehiculeService;
/**
 *
 * @author HP
 */
public class VehiculeTracker extends javax.swing.JInternalFrame {
private VehiculeGPSTrakerService vts;
     private TrackerService ts;
     private VehiculeService vs;
    private DefaultTableModel model;
    private static int id;
    /**
     * Creates new form VehiculeTracker
     */
     private void load() {
        model.setRowCount(0);
        for (VehiculeGPSTracker v : vts.findAll()) {
            model.addRow(new Object[]{
                v.getId(),
                v.getT(),
                v.getV(),
                v.getDateDebut(),
                v.getDateFin()
            });
        }
    }
        private void loadTrackers() {
        for (Tracker t : ts.findAll()) {
            listeTrackers1.addItem(t);
        }
    }
    private void loadVehicules() {
        for (Vehicule v : vs.findAll()) {
            Vehiculetxt1.addItem(v);
        }
    }
    public VehiculeTracker() {
         initComponents();
        vts = new VehiculeGPSTrakerService();
        ts = new TrackerService();
        vs = new VehiculeService();
        model = (DefaultTableModel) listeVT.getModel();
        load();
        loadTrackers();
        loadVehicules();
        jPanel2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeVT = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        listeTrackers1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DateDebuttxt1 = new com.toedter.calendar.JDateChooser();
        Add1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        DateFintxt1 = new com.toedter.calendar.JDateChooser();
        Vehiculetxt1 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Vehicule avec Les Trackers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 12))); // NOI18N

        listeVT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tracker", "Vehicule", "Date debut", "Date fin"
            }
        ));
        listeVT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeVTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeVT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Affecter / Desaffecter un Tracker", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 12))); // NOI18N

        listeTrackers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeTrackers1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel13.setText("Vehicule");

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setText("Date debut");

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel15.setText("Tracker");

        Add1.setFont(new java.awt.Font("Nirmala UI", 1, 10)); // NOI18N
        Add1.setText("Ajouter");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });

        update1.setFont(new java.awt.Font("Nirmala UI", 1, 10)); // NOI18N
        update1.setText("Modifier");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        delete1.setFont(new java.awt.Font("Nirmala UI", 1, 10)); // NOI18N
        delete1.setText("Supprimer");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel16.setText("Date Fin");

        Vehiculetxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehiculetxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateDebuttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listeTrackers1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateFintxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vehiculetxt1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vehiculetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listeTrackers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateFintxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDebuttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeVTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeVTMouseClicked
        id  = Integer.parseInt(model.getValueAt(listeVT.getSelectedRow(), 0).toString());
        listeTrackers1.setSelectedItem((Tracker) model.getValueAt(listeVT.getSelectedRow(), 1));
        Vehiculetxt1.setSelectedItem((Vehicule) model.getValueAt(listeVT.getSelectedRow(), 2));
        DateDebuttxt1.setDate((Date) model.getValueAt(listeVT.getSelectedRow(), 3));
        DateFintxt1.setDate((Date) model.getValueAt(listeVT.getSelectedRow(), 4));

    }//GEN-LAST:event_listeVTMouseClicked

    private void listeTrackers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeTrackers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listeTrackers1ActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
        Date dateDebut = DateDebuttxt1.getDate();
        Date dateFin = DateFintxt1.getDate();
        Tracker tracker = (Tracker) listeTrackers1.getSelectedItem();
        Vehicule vehicule = (Vehicule) Vehiculetxt1.getSelectedItem();
        if (vts.create(new VehiculeGPSTracker(dateDebut, dateFin, vehicule, tracker))){
            JOptionPane.showMessageDialog(this, "Tracker bien Affecté");
            load();
        }
    }//GEN-LAST:event_Add1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
        /* Position p = ps.findById(id);
        p.setLatitude(Double.parseDouble(latitudeTxt.getText()));
        p.setLongitude(Double.parseDouble(longitudeTxt.getText()));
        p.setDate(dateTxt.getDate());
        p.setTracker((Tracker) listeTrackers.getSelectedItem()); int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier ce position"); if (reponse == 0 && id != 0) {
            if (ps.update(p)) {
                JOptionPane.showMessageDialog(this, "Position modifié");
                loadPositins();
            }*/

            VehiculeGPSTracker v = vts.findById(id);
            v.setDateDebut(DateDebuttxt1.getDate());
            v.setDateFin(DateFintxt1.getDate());
            v.setV((Vehicule) Vehiculetxt1.getSelectedItem());
            v.setT((Tracker) listeTrackers1.getSelectedItem()); int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier ces champs"); if (reponse == 0 && id != 0); {
                if (vts.update(v)) {
                    JOptionPane.showMessageDialog(this, "Votre modification bien effectué ");
                    load();
                }
            }
    }//GEN-LAST:event_update1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous desaffecter ce tracker ?");
        if (reponse == 0 && id != 0) {
            if (vts.delete(vts.findById(id))) {
                JOptionPane.showMessageDialog(this, "Tracker Desaffecté avec succée");
                load();
            }
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void Vehiculetxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehiculetxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vehiculetxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private com.toedter.calendar.JDateChooser DateDebuttxt1;
    private com.toedter.calendar.JDateChooser DateFintxt1;
    private javax.swing.JComboBox Vehiculetxt1;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listeTrackers1;
    private javax.swing.JTable listeVT;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
